# Generated by Django 4.1.7 on 2023-06-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Aluno')),
                ('nome_professor', models.CharField(choices=[('professor1', 'Orlando'), ('professor2', 'Nilton'), ('professor3', 'Thiago'), ('professor4', 'Dhebora'), ('professor5', 'Amanda'), ('professor6', 'Marcelo')], max_length=50, verbose_name='Nome Professor')),
                ('disciplina', models.CharField(choices=[('disciplina1', 'DSM'), ('disciplina2', 'GE'), ('disciplina3', 'SI')], max_length=20, verbose_name='Disciplina')),
            ],
        ),
    ]
