# Generated by Django 4.1.7 on 2023-06-08 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listapresenca',
            name='disciplina',
            field=models.CharField(choices=[('DSM', 'Desenvolvimento de Software Multilataforma'), ('GE', 'Gestão Empresarial'), ('SI', 'Sistemas para Internet')], max_length=20, verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='listapresenca',
            name='nome_professor',
            field=models.CharField(choices=[('Orlando', 'Orlando'), ('Nilton', 'Nilton'), ('Thiago', 'Thiago'), ('Dhebora', 'Dhebora'), ('Amanda', 'Amanda'), ('Marcelo', 'Marcelo')], max_length=50, verbose_name='Nome Professor'),
        ),
    ]
